name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Grade Assignment
      id: grade-assignment
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Grade Assignment
        setup-command: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          -sSf | sh -s -- -y
        command: "~/.elan/bin/lake build && ~/.elan/bin/lake exe grade"
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADE-ASSIGNMENT_RESULTS: "${{steps.grade-assignment.outputs.result}}"
      with:
        runners: grade-assignment
